# Generated by Django 5.1.3 on 2025-01-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('inference_time', models.FloatField()),
                ('frame_id', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('image_size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streaming.imagesize')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(choices=[('person', 'Person'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('empty garbage', 'Empty Garbage'), ('full garbage', 'Full Garbage')], max_length=50)),
                ('confidence', models.FloatField()),
                ('area', models.FloatField(default=0.0)),
                ('bounding_box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streaming.boundingbox')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streaming.center')),
                ('inference_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='streaming.inferenceresult')),
            ],
        ),
    ]
