# Generated by Django 5.1.3 on 2025-01-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='bounding_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.boundingbox'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.center'),
        ),
        migrations.AlterField(
            model_name='inferenceresult',
            name='image_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.imagesize'),
        ),
    ]
