# Generated by Django 5.1.3 on 2025-01-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_detection_bounding_box_alter_detection_center_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.UniqueConstraint(fields=('x_min', 'y_min', 'x_max', 'y_max'), name='unique_bounding_box'),
        ),
        migrations.AddConstraint(
            model_name='center',
            constraint=models.UniqueConstraint(fields=('x', 'y'), name='unique_center'),
        ),
        migrations.AddConstraint(
            model_name='imagesize',
            constraint=models.UniqueConstraint(fields=('width', 'height'), name='unique_image_size'),
        ),
    ]
