# Generated by Django 5.1.3 on 2025-01-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_boundingbox_unique_bounding_box_center_unique_center_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagesize',
            name='unique_image_size',
        ),
    ]
