# Generated by Django 5.1.3 on 2025-01-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_remove_imagesize_unique_image_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boundingbox',
            name='unique_bounding_box',
        ),
        migrations.RemoveConstraint(
            model_name='center',
            name='unique_center',
        ),
    ]
