# Generated by Django 5.1.3 on 2025-01-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_remove_boundingbox_unique_bounding_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inferenceresult',
            name='zone',
        ),
        migrations.AlterField(
            model_name='detection',
            name='class_name',
            field=models.CharField(choices=[('person', 'Person'), ('car', 'Car'), ('taxi', 'Taxi'), ('bus', 'Bus'), ('truck', 'Truck'), ('empty garbage', 'Empty Garbage'), ('full garbage', 'Full Garbage'), ('garbage truck', 'Garbage Truck')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detection',
            name='inference_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='streaming.inferenceresult'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('people', 'People'), ('garbage', 'Garbage')], max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('timestamp_start', models.DateTimeField(blank=True, null=True)),
                ('timestamp_end', models.DateTimeField(blank=True, null=True)),
                ('first_detected_at', models.DateTimeField()),
                ('duration', models.FloatField(default=0.0)),
                ('bounding_box_ref', models.JSONField()),
                ('frame_count_missing', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('resolved', 'Resolved')], max_length=50)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.detection')),
                ('device_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.devicezone')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('parking', 'Parking'), ('garbage_truck', 'Garbage Truck Zone')], max_length=50)),
                ('bounding_box', models.JSONField()),
                ('device_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.devicezone')),
            ],
        ),
    ]
